CREATE DATABASE IF NOT EXISTS test;
USE test;
CREATE TABLE IF NOT EXISTS projects(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);
CREATE TABLE IF NOT EXISTS social_media(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);
